version: "3"
services:
  # database container
  mysql:
    image: mysql:$MYSQL_TAG
    container_name: "${PROJECT_NAME}_mysql"
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --disable-log-bin
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
    stop_grace_period: 30s
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD

  # Drupal with xdebug
  drupal:
    image: abbes/drupal9
    container_name: "${PROJECT_NAME}_drupal"
    build:
      context: ./docker/
      args:
        WEB_DOCUMENT_ROOT: $WEB_DOCUMENT_ROOT
        XDEBUG_REMOTE_HOST: $XDEBUG_REMOTE_HOST
    ports:
      - "${DRUPAL_PORT}:80"
    environment:
      XDEBUG_CONFIG: client_host=$XDEBUG_REMOTE_HOST
      PHP_IDE_CONFIG: "serverName=localhost"
      XDEBUG: 1
    expose:
      - 9003
    volumes:
      - ./:/var/www/html/
      - ./docker/conf/php.ini:/etc/php.ini
      - ./docker/conf/apache.conf:/etc/httpd/conf/httpd.conf
    depends_on:
      - mysql
    tty: true
